plugins:
  - stylelint-use-logical-spec
rules:
  color-named: never
  color-no-hex: null
  liberty/use-logical-spec:
    - always
extends:
  - '@siemens/stylelint-config-scss/stylelintrc.yml'
ignoreFiles:
  - dist/**
  - projects/**/dist/*.scss
