[project]
site_name = "@siemens/ngx-datatable"
site_description = "A feature-rich yet lightweight data-table crafted for Angular."
site_author = "Siemens AG"
copyright = "&copy; 2026 Siemens AG"
site_url = "https://siemens.github.io/ngx-datatable/"
docs_dir = "docs"
site_dir = "site"
extra_javascript = [{ path = "assets/ngx-datatable-examples/main.js", type = "module" }]
extra_css = [
    "assets/ngx-datatable-examples/styles.css",
    "assets/stylesheets/examples.css",
]

nav = [
    { "Introduction" = [
        "index.md",
        { "Getting Started" = "introduction/getting-started.md" },
        { "Features" = "introduction/features.md" },
        { "Modes" = "introduction/column-modes.md" },
        { "Architecture" = "introduction/architecture.md" },
        { "Theming" = "introduction/themes.md" },
        { "Change Detection" = "introduction/cd.md" },
    ] },
    { "API" = [
        "api/index.md",
    ] },
    { "Demos" = [
        { "Online" = "https://siemens.github.io/ngx-datatable/examples/" },
        { "Source Code" = "https://github.com/siemens/ngx-datatable/tree/main/src/app" },
    ] },
    { "Contributing" = [
        { "Building" = "contributing/building.md" },
        { "Guidelines" = "contributing/guidelines.md" },
        { "Community" = "contributing/community.md" },
        { "Credits" = "contributing/credits.md" },
    ] },
    { "Changelog" = "changelog.md" },
]

[project.theme]
variant = "modern"
features = [
    "navigation.indexes",
]

[project.repository]
url = "https://github.com/siemens/ngx-datatable"

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.zensical.extensions.macros]
module_name = "docs_extensions.datatable_example"

[project.markdown_extensions.pymdownx.blocks.details]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.superfences]
