// This file is generated by the example-routes builder. Do not edit manually.
import { Routes } from '@angular/router';
export const routes: Routes = [
    {
        path: '',
        redirectTo: 'fluid-row-height',
        pathMatch: 'full'
    },
    {
        path: 'bootstrap-theme',
        data: { sourcePath: 'basic/bootstrap-theme.component.ts' },
        loadComponent: () => import('./basic/bootstrap-theme.component').then(component => component.BootstrapThemeComponent)
    },
    {
        path: 'cell-selection',
        data: { sourcePath: 'selection/cell-selection.component.ts' },
        loadComponent: () => import('./selection/cell-selection.component').then(component => component.CellSelectionComponent)
    },
    {
        path: 'checkbox-selection',
        data: { sourcePath: 'selection/checkbox-selection.component.ts' },
        loadComponent: () => import('./selection/checkbox-selection.component').then(component => component.CheckboxSelectionComponent)
    },
    {
        path: 'client-side-paging',
        data: { sourcePath: 'paging/client-side-paging.component.ts' },
        loadComponent: () => import('./paging/client-side-paging.component').then(component => component.ClientSidePagingComponent)
    },
    {
        path: 'client-side-sorting',
        data: { sourcePath: 'sorting/client-side-sorting.component.ts' },
        loadComponent: () => import('./sorting/client-side-sorting.component').then(component => component.ClientSideSortingComponent)
    },
    {
        path: 'client-side-tree',
        data: { sourcePath: 'tree/client-side-tree.component.ts' },
        loadComponent: () => import('./tree/client-side-tree.component').then(component => component.ClientSideTreeComponent)
    },
    {
        path: 'column-pinning',
        data: { sourcePath: 'columns/column-pinning.component.ts' },
        loadComponent: () => import('./columns/column-pinning.component').then(component => component.ColumnPinningComponent)
    },
    {
        path: 'column-reorder',
        data: { sourcePath: 'columns/column-reorder.component.ts' },
        loadComponent: () => import('./columns/column-reorder.component').then(component => component.ColumnReorderComponent)
    },
    {
        path: 'column-toggling',
        data: { sourcePath: 'columns/column-toggling.component.ts' },
        loadComponent: () => import('./columns/column-toggling.component').then(component => component.ColumnTogglingComponent)
    },
    {
        path: 'comparator',
        data: { sourcePath: 'sorting/comparator.component.ts' },
        loadComponent: () => import('./sorting/comparator.component').then(component => component.ComparatorComponent)
    },
    {
        path: 'context-menu',
        data: { sourcePath: 'basic/context-menu.component.ts' },
        loadComponent: () => import('./basic/context-menu.component').then(component => component.ContextMenuComponent)
    },
    {
        path: 'css-classes',
        data: { sourcePath: 'basic/css-classes.component.ts' },
        loadComponent: () => import('./basic/css-classes.component').then(component => component.CssClassesComponent)
    },
    {
        path: 'custom-checkbox-selection',
        data: { sourcePath: 'selection/custom-checkbox-selection.component.ts' },
        loadComponent: () => import('./selection/custom-checkbox-selection.component').then(component => component.CustomCheckboxSelectionComponent)
    },
    {
        path: 'custom-template-summary',
        data: { sourcePath: 'summary/custom-template-summary.component.ts' },
        loadComponent: () => import('./summary/custom-template-summary.component').then(component => component.CustomTemplateSummaryComponent)
    },
    {
        path: 'dark-theme',
        data: { sourcePath: 'basic/dark-theme.component.ts' },
        loadComponent: () => import('./basic/dark-theme.component').then(component => component.DarkThemeComponent)
    },
    {
        path: 'default-sort',
        data: { sourcePath: 'sorting/default-sort.component.ts' },
        loadComponent: () => import('./sorting/default-sort.component').then(component => component.DefaultSortComponent)
    },
    {
        path: 'disable-selection-callback',
        data: { sourcePath: 'selection/disable-selection-callback.component.ts' },
        loadComponent: () => import('./selection/disable-selection-callback.component').then(component => component.DisableSelectionCallbackComponent)
    },
    {
        path: 'disabled',
        data: { sourcePath: 'basic/disabled.component.ts' },
        loadComponent: () => import('./basic/disabled.component').then(component => component.DisabledComponent)
    },
    {
        path: 'drag-drop',
        data: { sourcePath: 'drag-drop/drag-drop.component.ts' },
        loadComponent: () => import('./drag-drop/drag-drop.component').then(component => component.DragDropComponent)
    },
    {
        path: 'dynamic-row-height',
        data: { sourcePath: 'basic/dynamic-row-height.component.ts' },
        loadComponent: () => import('./basic/dynamic-row-height.component').then(component => component.DynamicRowHeightComponent)
    },
    {
        path: 'empty-template',
        data: { sourcePath: 'basic/empty-template.component.ts' },
        loadComponent: () => import('./basic/empty-template.component').then(component => component.EmptyTemplateComponent)
    },
    {
        path: 'filtering',
        data: { sourcePath: 'basic/filtering.component.ts' },
        loadComponent: () => import('./basic/filtering.component').then(component => component.FilteringComponent)
    },
    {
        path: 'fixed-column',
        data: { sourcePath: 'columns/fixed-column.component.ts' },
        loadComponent: () => import('./columns/fixed-column.component').then(component => component.FixedColumnComponent)
    },
    {
        path: 'fixed-row-height',
        data: { sourcePath: 'basic/fixed-row-height.component.ts' },
        loadComponent: () => import('./basic/fixed-row-height.component').then(component => component.FixedRowHeightComponent)
    },
    {
        path: 'flex-column',
        data: { sourcePath: 'columns/flex-column.component.ts' },
        loadComponent: () => import('./columns/flex-column.component').then(component => component.FlexColumnComponent)
    },
    {
        path: 'fluid-row-height',
        data: { sourcePath: 'basic/fluid-row-height.component.ts' },
        loadComponent: () => import('./basic/fluid-row-height.component').then(component => component.FluidRowHeightComponent)
    },
    {
        path: 'footer-template',
        data: { sourcePath: 'basic/footer-template.component.ts' },
        loadComponent: () => import('./basic/footer-template.component').then(component => component.FooterTemplateComponent)
    },
    {
        path: 'force-column',
        data: { sourcePath: 'columns/force-column.component.ts' },
        loadComponent: () => import('./columns/force-column.component').then(component => component.ForceColumnComponent)
    },
    {
        path: 'full-screen',
        data: { sourcePath: 'basic/full-screen.component.ts' },
        loadComponent: () => import('./basic/full-screen.component').then(component => component.FullScreenComponent)
    },
    {
        path: 'full-screen-tree',
        data: { sourcePath: 'tree/full-screen-tree.component.ts' },
        loadComponent: () => import('./tree/full-screen-tree.component').then(component => component.FullScreenTreeComponent)
    },
    {
        path: 'hidden-on-load',
        data: { sourcePath: 'basic/hidden-on-load.component.ts' },
        loadComponent: () => import('./basic/hidden-on-load.component').then(component => component.HiddenOnLoadComponent)
    },
    {
        path: 'horz-vert-scrolling',
        data: { sourcePath: 'basic/horz-vert-scrolling.component.ts' },
        loadComponent: () => import('./basic/horz-vert-scrolling.component').then(component => component.HorzVertScrollingComponent)
    },
    {
        path: 'inline-editing',
        data: { sourcePath: 'basic/inline-editing.component.ts' },
        loadComponent: () => import('./basic/inline-editing.component').then(component => component.InlineEditingComponent)
    },
    {
        path: 'inline-html-summary',
        data: { sourcePath: 'summary/inline-html-summary.component.ts' },
        loadComponent: () => import('./summary/inline-html-summary.component').then(component => component.InlineHtmlSummaryComponent)
    },
    {
        path: 'inline-template',
        data: { sourcePath: 'templates/inline-template.component.ts' },
        loadComponent: () => import('./templates/inline-template.component').then(component => component.InlineTemplateComponent)
    },
    {
        path: 'large-data-set',
        data: { sourcePath: 'basic/large-data-set.component.ts' },
        loadComponent: () => import('./basic/large-data-set.component').then(component => component.LargeDataSetComponent)
    },
    {
        path: 'live-data',
        data: { sourcePath: 'basic/live-data.component.ts' },
        loadComponent: () => import('./basic/live-data.component').then(component => component.LiveDataComponent)
    },
    {
        path: 'multi-click-and-checkbox-selection',
        data: { sourcePath: 'selection/multi-click-and-checkbox-selection.component.ts' },
        loadComponent: () => import('./selection/multi-click-and-checkbox-selection.component').then(component => component.MultiClickAndCheckboxSelectionComponent)
    },
    {
        path: 'multi-click-row-selection',
        data: { sourcePath: 'selection/multi-click-row-selection.component.ts' },
        loadComponent: () => import('./selection/multi-click-row-selection.component').then(component => component.MultiClickRowSelectionComponent)
    },
    {
        path: 'multi-row-selection',
        data: { sourcePath: 'selection/multi-row-selection.component.ts' },
        loadComponent: () => import('./selection/multi-row-selection.component').then(component => component.MultiRowSelectionComponent)
    },
    {
        path: 'multiple-tables',
        data: { sourcePath: 'basic/multiple-tables.component.ts' },
        loadComponent: () => import('./basic/multiple-tables.component').then(component => component.MultipleTablesComponent)
    },
    {
        path: 'responsive',
        data: { sourcePath: 'basic/responsive.component.ts' },
        loadComponent: () => import('./basic/responsive.component').then(component => component.ResponsiveComponent)
    },
    {
        path: 'row-detail',
        data: { sourcePath: 'basic/row-detail.component.ts' },
        loadComponent: () => import('./basic/row-detail.component').then(component => component.RowDetailComponent)
    },
    {
        path: 'row-grouping',
        data: { sourcePath: 'basic/row-grouping.component.ts' },
        loadComponent: () => import('./basic/row-grouping.component').then(component => component.RowGroupingComponent)
    },
    {
        path: 'rxjs',
        data: { sourcePath: 'basic/rxjs.component.ts' },
        loadComponent: () => import('./basic/rxjs.component').then(component => component.RxjsComponent)
    },
    {
        path: 'scrolling-no-virtual',
        data: { sourcePath: 'paging/scrolling-no-virtual.component.ts' },
        loadComponent: () => import('./paging/scrolling-no-virtual.component').then(component => component.ScrollingNoVirtualComponent)
    },
    {
        path: 'scrolling-server-side',
        data: { sourcePath: 'paging/scrolling-server-side.component.ts' },
        loadComponent: () => import('./paging/scrolling-server-side.component').then(component => component.ScrollingServerSideComponent)
    },
    {
        path: 'server-side-paging',
        data: { sourcePath: 'paging/server-side-paging.component.ts' },
        loadComponent: () => import('./paging/server-side-paging.component').then(component => component.ServerSidePagingComponent)
    },
    {
        path: 'server-side-paging-summary',
        data: { sourcePath: 'summary/server-side-paging-summary.component.ts' },
        loadComponent: () => import('./summary/server-side-paging-summary.component').then(component => component.ServerSidePagingSummaryComponent)
    },
    {
        path: 'server-side-sorting',
        data: { sourcePath: 'sorting/server-side-sorting.component.ts' },
        loadComponent: () => import('./sorting/server-side-sorting.component').then(component => component.ServerSideSortingComponent)
    },
    {
        path: 'simple-summary',
        data: { sourcePath: 'summary/simple-summary.component.ts' },
        loadComponent: () => import('./summary/simple-summary.component').then(component => component.SimpleSummaryComponent)
    },
    {
        path: 'single-row-selection',
        data: { sourcePath: 'selection/single-row-selection.component.ts' },
        loadComponent: () => import('./selection/single-row-selection.component').then(component => component.SingleRowSelectionComponent)
    },
    {
        path: 'summary-row-actions',
        data: { sourcePath: 'summary/summary-row-actions.component.ts' },
        loadComponent: () => import('./summary/summary-row-actions.component').then(component => component.SummaryRowActionsComponent)
    },
    {
        path: 'template-ref',
        data: { sourcePath: 'templates/template-ref.component.ts' },
        loadComponent: () => import('./templates/template-ref.component').then(component => component.TemplateRefComponent)
    },
    {
        path: 'vert-dynamic-scrolling',
        data: { sourcePath: 'basic/vert-dynamic-scrolling.component.ts' },
        loadComponent: () => import('./basic/vert-dynamic-scrolling.component').then(component => component.VertDynamicScrollingComponent)
    },
    {
        path: 'virtual-server-side',
        data: { sourcePath: 'paging/virtual-server-side.component.ts' },
        loadComponent: () => import('./paging/virtual-server-side.component').then(component => component.VirtualServerSideComponent)
    }
];
